apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sckv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sckv
    app.kubernetes.io/part-of: ci10t-776-0028-app
  name: devfile-sample-sckv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sckv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sckv
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0028-tenant/ci10t-776-0028-app/devfile-sample-sckv@sha256:9a7046900d64fe9dcefe407f450bac319b7e05a9775d2c8d3172e564db1a0018
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
